#! /usr/bin/env python
import sys
import random


# Reads the board in
def readBoard(board):
    file = open(board, 'r')
    return parseBoard(file)

# Parses the board
def parseBoard(file):
    count = file.read(1)  # turn number
    turn = file.read(2)   # white or black
    lines = file.readlines() # the rest of the lines
    del lines[0:1] # get rid of the +----+
    del lines[-3:-1] # get rid of the bottom rows
      
    state

    for line in lines:
       # to implement later, generate state
    
    return (count, turn, state) 

# Random function that
# picks starting positions based off a turns color
# These are predefined as good starting positions.
def randSetup(turn):
   if turn == 'w':
     setup = ['Ee2 Md2 Ca1 Dc2 Hb2 Hg2 Ch1 Df2 Rb1 Rc1 Rd1 Re1 Rf1 Rg1 Ra2 Rh2',
              'Ee2 Md2 Da1 Hb2 Dh1 Hg2 Cf1 Cc1 Rb1 Rd1 Re1 Rg1 Ra2 Rc2 Rf2 Rh2',
              'Ee2 Md2 Hh2 Dg2 Db1 Ca2 He1 Cf1 Ra1 Rc1 Rd1 Rg1 Rh1 Rb2 Rc2 Rf2',
              'Ee2 Md2 Ha2 Hh2 Db2 Dg2 Cc2 Cf2 Ra1 Rb1 Rc1 Rd1 Re1 Rf1 Rg1 Rh1']
   else:
     setup = ['ee7 md7 ha7 hh7 db7 dg7 cf8 cc8 rc7 rf7 ra8 rb8 rd8 re8 rg8 rh8',
              'ha7 hh7 dg7 me7 ed7 cc8 cf8 da8 rb7 rc7 rf7 rb8 rd8 re8 rg8 rh8',
              'ee7 md7 ha7 hh7 db7 dg7 cf8 cc8 rc7 rf7 ra8 rb8 rd8 re8 rg8 rh8',
              'me7 ed7 ha7 hh7 db7 dg7 cc8 cf8 rc7 rf7 ra8 rb8 rd8 re8 rg8 rh8']

     return setup[random.randint(0,3)]
   
board = sys.argv[1]
(count, turn, state) = readBoard(board)

# Setup Board
if count == 1:
  print randSetup(turn)
  quit()
else:
  # zobrist_hash(state)
  # find best move based on minimax
